name = "mmdedgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
[vars]
ADMIN = "mmd4567nne88l"

[[kv_namespaces]]
binding = "KV"
id = "d3fe2c8ba5aa47549bb0a555cfcc1767"
